### ISSUE TITLE
requests to added

### ISSUE THREAD

**Issue by infotun2** [oormicreations/PredictEd#2]
hi,

Thank you for this great tool, it's possible to add a window at the bottom of the software that displays some sentences from context and from my own typed. To get ideas from my past writing. like in translation tools Is doing a fuzzy search to get the best sentences by % of similarity.

Thank you 

walid

**Comment by oormicreations** [comment]
Hi
Unfortunately, it is not being developed now. I shifted to Linux. But hopefully someone can fork it and add this function.

**Comment by infotun2** [comment]
Thank you for your reply, and good luck for your future projects!
